melhorado os shell-scripts

diff --git a/bin/start b/bin/start
--- a/bin/start
+++ b/bin/start
@@ -4,10 +4,13 @@ DIR="$( cd -P "$( dirname "$0" )" && pwd )"
 cd $DIR
 cd ..
 
-docker-compose up -d dev redis
+abort() {
+	printf "\n  \033[31mError: $@\033[0m\n\n" && exit 1
+}
+
+docker-compose up $1 -d dev redis
 if test $? -ne 0; then
-	printf "${RED}Docker Compose Failed${NC}\n"
-	exit -1
+	abort "Docker Compose Failed"
 fi
 
 exit 0
diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -4,12 +4,15 @@ DIR="$( cd -P "$( dirname "$0" )" && pwd )"
 cd $DIR
 cd ..
 
-RED='\033[0;31m'
-GREEN='\033[0;32m'
-NC='\033[0m'
-
 NAMESPACE='cepkoa'
-REBUILD=0
+
+abort() {
+	printf "\n  \033[31mError: $@\033[0m\n\n" && exit 1
+}
+
+ok() {
+	printf "\n  \033[32mOk: $@\033[0m\n\n"
+}
 
 _cleanup() {
 	docker-compose down --volumes > /dev/null 2>&1
@@ -22,34 +25,17 @@ _up() {
 	docker-compose -p $NAMESPACE up $1 -d dev redis
 }
 
-args=()
-options='b'
-while getopts $options option
-do
-	case $option in
-		b) REBUILD=1;;
-		\?) echo "Unknown option: -$OPTARG" >&2; exit 1;;
-		:) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
-		*) echo "Unimplemented option: -$OPTARG" >&2; exit 1;;
-	esac
-done
+trap '_cleanup; abort "Tests Failed For Unexpected Reasons"' HUP INT QUIT PIPE TERM SIGINT SIGTERM
 
-trap '_cleanup; printf "${RED}Tests Failed For Unexpected Reasons${NC}\n"; exit 1' HUP INT QUIT PIPE TERM SIGINT SIGTERM
-
-test $REBUILD == 1 && _up '--build' || _up
+_up $1
 if test $? -ne 0; then
-	printf "${RED}Docker Compose Failed${NC}\n"
-	exit -1
+	abort "Docker Compose Failed"
 fi
 
 docker-compose -p ${NAMESPACE} up test
 TEST_EXIT_CODE=`docker inspect ${NAMESPACE}_test_1 --format='{{.State.ExitCode}}'`
 
-if test $TEST_EXIT_CODE -ne 0; then
-	printf "${RED}Test FAIL${NC}\n"
-else
-	printf "${GREEN}Test OK${NC}\n"
-fi
+test $TEST_EXIT_CODE -ne 0 && abort "Test FAIL" || ok "Test PASS"
 
 _cleanup
 
