update deps, devDeps and docker stuff

diff --git a/bin/stop b/bin/stop
--- a/bin/stop
+++ b/bin/stop
@@ -1,16 +1,38 @@
 #!/bin/bash
 
-DIR="$( cd -P "$( dirname "$0" )" && pwd )"
-cd $DIR
-cd ..
-
 abort() {
 	printf "\n  \033[31mError: $@\033[0m\n\n" && exit 1
 }
 
-docker-compose down --volumes --remove-orphans
-if test $? -ne 0; then
-	abort "Docker Compose Failed"
+ok() {
+	printf "\n  \033[32mOk: $@\033[0m\n\n"
+}
+
+DIR="$( cd -P "$( dirname "$0" )" && pwd )"
+cd $DIR
+cd ..
+
+CURR_FOLDER=`pwd`
+OPT="development"
+COMPOSE_TEMPLATE="${CURR_FOLDER}/docker-compose.template.yml"
+COMPOSE_LOCAL="${CURR_FOLDER}/docker-compose.local.yml"
+
+# ENV File
+ENVFILE="${CURR_FOLDER}/.env-${OPT}"
+if test ! -e $ENVFILE; then
+	abort "Environment file not found"
 fi
+
+set -a
+source $ENVFILE
+
+docker-compose \
+	-f $COMPOSE_TEMPLATE \
+	-f $COMPOSE_LOCAL \
+	down \
+	--volumes \
+	--remove-orphans
+
+test $? -ne 0 && abort "Docker Compose Failed" || ok "Stopped"
 
 exit 0
diff --git a/bin/test b/bin/test
--- a/bin/test
+++ b/bin/test
@@ -4,6 +4,14 @@ DIR="$( cd -P "$( dirname "$0" )" && pwd )"
 cd $DIR
 cd ..
 
+CURR_FOLDER=`pwd`
+BUILD=""
+SERVICE="cep"
+OPT="test"
+COMPOSE_TEMPLATE="${CURR_FOLDER}/docker-compose.template.yml"
+COMPOSE_LOCAL="${CURR_FOLDER}/docker-compose.local.yml"
+COMPOSE_TEST="${CURR_FOLDER}/docker-compose.test.yml"
+
 abort() {
 	printf "\n  \033[31mError: $@\033[0m\n\n" && exit 1
 }
@@ -12,22 +20,69 @@ ok() {
 	printf "\n  \033[32mOk: $@\033[0m\n\n"
 }
 
-_cleanup() {
-	docker-compose down --volumes --remove-orphans > /dev/null 2>&1
-	# docker rmi $(docker images --filter=reference='*:test' -q) > /dev/null 2>&1
+usage() {
+	cat <<-EOF
+
+  Usage: $0 [-b] [-s <service>]
+
+  Options:
+    -b   Build image
+    -s   Docker compose service name
+    -h   Show usage
+
+EOF
+exit 0
 }
 
-trap '_cleanup; abort "Tests Failed For Unexpected Reasons"' HUP INT QUIT PIPE TERM SIGINT SIGTERM
+_cleanup() {
+	docker-compose \
+		-f $COMPOSE_TEMPLATE \
+		-f $COMPOSE_LOCAL \
+		-f $COMPOSE_TEST \
+		down \
+		--volumes \
+		--remove-orphans > /dev/null 2>&1
+}
 
-docker-compose up $1 --force-recreate test
-if test $? -ne 0; then
-	abort "Docker Compose Failed"
+trap '_cleanup; abort "Tests failed for unexpected reasons"' HUP INT QUIT PIPE TERM SIGINT SIGTERM
+
+while getopts ":bs:" o
+do
+	case ${o} in
+		b) BUILD="--build" ;;
+		s) SERVICE=$OPTARG ;;
+		*) usage ;;
+	esac
+done
+
+# ENV File
+ENVFILE="${CURR_FOLDER}/.env-${OPT}"
+if test ! -e $ENVFILE; then
+	abort "Environment file not found"
 fi
 
-TEST_EXIT_CODE=`docker inspect test --format='{{.State.ExitCode}}'`
+set -a
+source $ENVFILE
+
+docker-compose \
+	-f $COMPOSE_TEMPLATE \
+	-f $COMPOSE_LOCAL \
+	-f $COMPOSE_TEST \
+	up \
+	--force-recreate \
+	--always-recreate-deps \
+	--abort-on-container-exit \
+	--exit-code-from $SERVICE \
+	--remove-orphans \
+	$BUILD \
+	$SERVICE
+
+if test $? -ne 0; then
+	_cleanup
+	abort "Test FAIL"
+fi
 
 _cleanup
+ok "Test PASS"
 
-test $TEST_EXIT_CODE -ne 0 && abort "Test FAIL" || ok "Test PASS"
-
-exit $TEST_EXIT_CODE
+exit 0
