update packs and version

diff --git a/bin/local/start b/bin/local/start
--- a/bin/local/start
+++ b/bin/local/start
@@ -6,11 +6,37 @@ BIN_DIR="$(cd $DIR/.. && pwd)"
 # Import functions
 . $BIN_DIR/helper/fn
 
+# Usage
+usage() {
+	cat <<-EOF
+
+  Usage: $0 [-w]
+
+  Options:
+    -w     Watch and reload application
+    -h     Show usage
+
+EOF
+exit 2
+}
+
 # Go to current directory
 CURR_FOLDER="$(pwd)"
 cd $CURR_FOLDER
 
 OPT="development"
+
+unset WATCH
+WATCH=false
+
+while getopts "wh" o
+do
+	case ${o} in
+		w) WATCH=true ;;
+		h) usage ;;
+		\?) usage ;;
+	esac
+done
 
 # ENV File
 load_env $OPT
@@ -20,6 +46,17 @@ if test "${REQUIRE_GEN:-0}" = "1"; then
 	gen_env "${CURR_FOLDER}/resource/env.js"
 fi
 
-$START_CMD
+if $WATCH; then
+	ok "Running cmd: ${WATCH_LOCAL_CMD}"
+
+	# Watch command
+	eval ${WATCH_LOCAL_CMD}
+
+	if test $? -ne 0; then
+		abort "Watch failed"
+	fi
+else
+	$START_CMD
+fi
 
 exit 0
