back to redis

diff --git a/bin/docker/image b/bin/docker/image
--- a/bin/docker/image
+++ b/bin/docker/image
@@ -1,9 +1,10 @@
 #!/bin/bash
 
-DIR="$( cd -P "$( dirname "$0" )" && pwd )"
+DIR="$(cd $(dirname $0) && pwd)"
+BIN_DIR="$(cd $DIR/.. && pwd)"
 
 # Import functions
-. $DIR/_fn
+. $BIN_DIR/helper/fn
 
 usage() {
 	cat <<-EOF
@@ -18,11 +19,10 @@ EOF
 exit 0
 }
 
-# Go to project root
-cd $DIR
-cd ..
+# Go to current directory
+CURR_FOLDER="$(pwd)"
+cd $CURR_FOLDER
 
-CURR_FOLDER="$( pwd )"
 OPT="staging"
 
 while getopts ":e:" o
@@ -33,32 +33,34 @@ do
 	esac
 done
 
-if test -z ${OPT}; then
-	abort "Missing environment"
+# ENV File
+load_env $OPT
+
+# Generate ENVs for frontend application
+if test "${REQUIRE_GEN:-0}" = "1"; then
+	gen_env "${CURR_FOLDER}/resource/env.js"
 fi
 
-# ENV File
-load_env $CURR_FOLDER $OPT
-
-## Variables
-REGISTRY_USER="$( cat ${CURR_FOLDER}/.registry-user )"
-REGISTRY_PASSWD="$( cat ${CURR_FOLDER}/.registry-passwd )"
+# Variables
+REGISTRY_USER="$(cat ${CURR_FOLDER}/.registry-user)"
+REGISTRY_PASSWD="$(cat ${CURR_FOLDER}/.registry-passwd)"
 TAG_IMAGE="${REGISTRY}/${IMAGE}:${VERSION}"
 
-## Build
+# Build
 docker build \
 	--build-arg NODE_ENV=${NODE_ENV} \
-	--build-arg APP_ENV=${APP_ENV} \
-	--build-arg APP_NS=${APP_NS} \
-	--build-arg VERSION=${VERSION} \
-	--compress --force-rm --no-cache . --tag $TAG_IMAGE
-test $? -ne 0 && abort "Falha no build da image --> ${build}" || ok "Build image ok --> ${build}"
+	--target main \
+	--compress \
+	--force-rm \
+	--no-cache . --tag $TAG_IMAGE
 
-## Push (Send image to Registry)
+test $? -ne 0 && abort "Falha no build da image --> ${TAG_IMAGE}" || ok "Build image ok --> ${TAG_IMAGE}"
+
+# Push (Send image to Registry)
 cat ${CURR_FOLDER}/.registry-passwd | docker login $REGISTRY --username $REGISTRY_USER --password-stdin
 docker push $TAG_IMAGE
 
-# Cleanup
+# # Cleanup
 # docker rmi $(docker images -q -f "dangling=true" -f "label=autodelete=true")
 
 ok "Build finalizado... Yeahh!!!"
diff --git a/bin/docker/start b/bin/docker/start
--- a/bin/docker/start
+++ b/bin/docker/start
@@ -1,9 +1,10 @@
 #!/bin/bash
 
-DIR="$( cd -P "$( dirname "$0" )" && pwd )"
+DIR="$(cd $(dirname $0) && pwd)"
+BIN_DIR="$(cd $DIR/.. && pwd)"
 
 # Import functions
-. $DIR/_fn
+. $BIN_DIR/helper/fn
 
 usage() {
 	cat <<-EOF
@@ -20,22 +21,16 @@ EOF
 exit 0
 }
 
-# Go to project root
-cd $DIR
-cd ..
+# Go to current directory
+CURR_FOLDER="$(pwd)"
+cd $CURR_FOLDER
 
-CURR_FOLDER="$( pwd )"
 BUILD=""
+SERVICE=""
 DAEMON="--abort-on-container-exit"
 OPT="development"
-SERVICE=""
 COMPOSE_TEMPLATE="${CURR_FOLDER}/docker-compose.template.yml"
 COMPOSE_LOCAL="${CURR_FOLDER}/docker-compose.local.yml"
-
-export DOCKERFILE="${CURR_FOLDER}/Dockerfile.dev"
-export ARG_ENTR_INOTIFY_WORKAROUND=`test $(uname) = 'Linux' && echo 0 || echo 1`
-export USER_ID="$( id -u )"
-export GROUP_ID="$( id -g )"
 
 while getopts ":bds:" o
 do
@@ -48,9 +43,14 @@ do
 done
 
 # ENV File
-load_env $CURR_FOLDER $OPT
+load_env $OPT
 
-docker-compose \
+# Generate ENVs for frontend application
+if test "${REQUIRE_GEN:-0}" = "1"; then
+	gen_env "${CURR_FOLDER}/resource/env.js"
+fi
+
+docker compose \
 	-f $COMPOSE_TEMPLATE \
 	-f $COMPOSE_LOCAL \
 	up \
@@ -61,5 +61,7 @@ docker-compose \
 	$BUILD \
 	$DAEMON \
 	$SERVICE
+
+test $? -ne 0 && abort "Docker Compose up failed" || ok "Stopped gracefully"
 
 exit 0
diff --git a/bin/helper/wait b/bin/helper/wait
--- a/bin/helper/wait
+++ b/bin/helper/wait
@@ -3,18 +3,18 @@
 : ${SLEEP_LENGTH:=2}
 : ${TIMEOUT_LENGTH:=60}
 
-DIR="$( cd -P "$( dirname "$0" )" && pwd )"
+DIR="$(cd $(dirname $0) && pwd)"
+BIN_DIR="$(cd $DIR/.. && pwd)"
 
 # Import functions
-. $DIR/_fn
+. $BIN_DIR/helper/fn
 
 wait_for() {
-	START="$( date +%s )"
+	START="$(date +%s)"
 	echo "Waiting for $1 to listen on $2..."
-	while ! nc -z $1 $2;
-		do
+	while ! nc -z $1 $2; do
 		if [ $(($(date +%s) - $START)) -gt $TIMEOUT_LENGTH ]; then
-				abort "Service $1:$2 did not start within $TIMEOUT_LENGTH seconds. Aborting..."
+			abort "Service $1:$2 did not start within $TIMEOUT_LENGTH seconds. Aborting..."
 		fi
 		echo "sleeping"
 		sleep $SLEEP_LENGTH
